### PR TITLE
Added courses to context. Code changes for new firestore course structure

### PR DESCRIPTION
**Pull request by avinashupadhya99**
Does your PR solve any issues/bugs opened or raised in this repo?

- [ ] Yes
- [x] No

If you've mentioned **Yes** above, then mention the Issue no here (with #), else ignore it:

**Issue No or name**: N/A

Is it a bug fix, security fix, feature update, UI Update or other?

- [x] Backend Fix
- [ ] Bug fix
- [x] Feature Update
- [ ] Page addition
- [x] UI Fix
- [ ] Other

Description of what you did:

 - The structure of how the courses are stored in the Firestore is changed. Instead of having the course name as the document ID, a course ID like `DH001` will be used  and the course name will be a field inside the document. The field `courseJSON` is renamed to `lessons`. 
 - This PR makes the necessary changes in `ExistUser.js` for the new course structure. 
 - The courses are now stored in the context and fetched from there. 
 - The `courses` context is an object with the courseID as the key.
 - The `enrolledCourses` for an user is also an object with the courseID as the key and the index of the lesson array stored as `currentLessonNumber` in the enrolledCourses object. This way the user progress can be tracked for each course by knowing the lesson.
 - The existuser page will display all courses available and an `Enroll`/`Unenroll` button as applicable.

Screenshots - 

DefHacks

If page addition is marked, mention the page name here:

N/A

Have you notified this PR in the issue? [OPTIONAL] (so that we can check in case of issue fix)

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Review by andytubeee — DISMISSED** [review]

**Comment by AnnLe4869** [comment]
You did a good job :)
However there are some changes you could do to make it better
1. When you store all courses you should store them as an array and not object. This would make it easier to loop through, filter them out, etc. 
2. You don't need to use `onSnapshot` to listen to the change of `enrolledCourses`  from `firestore`. Reason is that the change only come from us. For example if user want to enroll in a course or unenroll from one, you can update the app state and then update in the `firestore` with `update` and we only need to know whether that update is success or not. `onSnapshot` should be used in situation where multiple people make change to the app and the change need to be update immediately (for example a chat app)
3. You can refactor the variables' name a bit. Like from `USER_ID` to `userId`

With that saying, these are recommendation of how to make the app better. Not that the points above cause the app to crash or significantly slow it down. 

Also did you test it? Does it work?

**Review by AnnLe4869 — DISMISSED** [review]

**Comment by avinashupadhya99** [comment]
> 1. When you store all courses you should store them as an array and not object. This would make it easier to loop through, filter them out, etc.

The reason why it is stored as an object because it is easier to access it by it's key(CourseID) when required for accessing individual courses. It can be looped easily by using `Object.keys(courses)` as the array. It can also be deleted easily using the `delete` keyword. So I figured it covers all those and used object.

> 2. You don't need to use `onSnapshot` to listen to the change of `enrolledCourses`  from `firestore`. Reason is that the change only come from us. For example if user want to enroll in a course or unenroll from one, you can update the app state and then update in the `firestore` with `update` and we only need to know whether that update is success or not. `onSnapshot` should be used in situation where multiple people make change to the app and the change need to be update immediately (for example a chat app)

Yep, thought so. It was onSnapshot earlier and I didn't change that thinking it would update if changes were made in another tab/window. But this seems unnecessary. I will change it.

> 3. You can refactor the variables' name a bit. Like from `USER_ID` to `userId`

Got it. Will do this.

> Also did you test it? Does it work?

I have tested it, it works for all the cases I could think of.

**Review by AnnLe4869 — APPROVED** [review]

**Comment by AnnLe4869** [comment]
> It can be looped easily by using `Object.keys(courses)` as the array

This is true, but it's limited to the object key only. If you want to get all the values (let say you want to display all the courses' content this will be inconvenient

> It can also be deleted easily using the `delete` keyword

Most of the time (if not always) you should never modify a state variable directly. You normally `setState` to the new value instead. Even when you try to clone the object into new variable you still risk of directly modifying the state variable.

**Comment by avinashupadhya99** [comment]
> > It can be looped easily by using `Object.keys(courses)` as the array
> 
> This is true, but it's limited to the object key only. If you want to get all the values (let say you want to display all the courses' content this will be inconvenient

It would be the same thing. Instead of looping through the array, we would loop through the `Object.keys(courses)` array.

> > It can also be deleted easily using the `delete` keyword
> 
> Most of the time (if not always) you should never modify a state variable directly. You normally `setState` to the new value instead. Even when you try to clone the object into new variable you still risk of directly modifying the state variable.

I think updating an array and updating an object is pretty much the same thing. It would require copying the previous state and updating that. The data structure for the state should not matter in my opinion. And objects can be filtered by looping through them which is the same time complexity of `filter` for array and almost similar code.
Please let me know if I am wrong in any of these. I like objects because they are easy to fetch by key which is most of our purposes I feel.

**Review by andytubeee — APPROVED** [review]

**Pull request merged**
