### PR TITLE
Change Nav to Link DOMs in Navbar and add ESLint YAML file

### PR DESCRIPTION
**Pull request by alphaX86**
If you're opening a pull request for this repo, then do answer a few questions below, before submitting!

Does your PR solve any issues/bugs opened or raised in this repo?

- [x] Yes
- [ ] No

If you've mentioned **Yes** above, then mention the Issue no here (with #), else ignore it:

**Issue No or Name**: Change all Navbar links to DOM Format

Is it a bug fix, security fix, feature update, UI Update or other?

- [ ] Backend Fix
- [x] Bug fix
- [x] Feature Update
- [ ] Page addition
- [x] UI Fix
- [ ] Other

Description of what you did:

If page addition is marked, mention the page name here:

Have you notified this PR in the issue? [OPTIONAL] (so that we can check in case of issue fix)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alphaX86** [comment]
Addl point: An ESLint workflow is also added to confirm if the changes exactly follow the lint rules. I haven't tested it in GitHub, so it may need editing!

**Comment by alphaX86** [comment]
Lint YML now works and has no issues to merge now! ;)

**Review by GedionT — COMMENTED** [review]
seems fine. ✔️

**Review by GedionT — APPROVED** [review]
👍🏽 merging, but recent changes from nav component might need minor updates

**Comment by alphaX86** [comment]
OK, will note that in the board @GedionT 👍

**Comment by GedionT** [comment]
@alphaX86 like I suspected, the nav has unnecessary and duplicate links, if you could remove that and follow the previous navbar commit, it would be nice.

**Comment by alphaX86** [comment]
Well, I thought that if the Navbar is changed to DOM it'd be nice as stated in boards, but well, I'll revert them then

**Pull request merged**
