### PR TITLE
Update: Added dummy code editor

### PR DESCRIPTION
**Pull request by andytubeee**
If you're opening a pull request for this repo, then do answer a few questions below, before submitting it!

Does your PR solve any issues opened or raised in this repo or from the project's bug section?
  - [ ] Yes
  - [X] No
  
If you've mentioned **Yes** above, then mention the Issue no here (with #), else ignore it:

**Issue No**: 

Is it a bug fix, security fix, feature update, UI Update or other?
  - [ ] Bug fix (related to Firebase, backend etc)
  - [X] Feature Update
  - [ ] Page addition
  - [ ] UI Fix
  - [ ] Other
  
If you've mentioned Other, then state your answer here (like what actually is and that):

I have added a dummy code editor using draft-js. Please run `npm install` again. The code editor is a dummy which means the output is the same as the input.

If page addition is marked, mention the page name here:

Have you notified this PR of the issue? [OPTIONAL] (so that we can check in case of issue fix)
  - [ ] Yes
  - [X] No

### CODE REVIEW

**Comment by GedionT** [comment]
Can you fix the Conflicts and refactor the use of .jsx to .js to keep consistency between components? Maybe create another PR after that @andytubeee?

**Comment by andytubeee** [comment]
@GedionT Hi, sorry for the late reply, yes I have merged that conflicting files and renamed it to JS. However, in react, it is actually supposed to be JSX, rather than Js, but for consistency, I renamed it to JS, please merge my changes with the master branch. Thanks!

**Comment by GedionT** [comment]
> @GedionT Hi, sorry for the late reply, yes I have merged that conflicting files and renamed it to JS. However, in react, it is actually supposed to be JSX, rather than Js, but for consistency, I renamed it to JS, please merge my changes with the master branch. Thanks!

> @andytubeee It's okay. Awesome, I'll review and merge. The use of JSX and JS won't bring an issue. Although react uses jsx natively, Webpack and babel allows us to comfortably choose whichever format we choose to use.

**Review by GedionT — APPROVED** [review]
👍🏽 it's a go

**Pull request merged**
